var app=angular.module('app',['ng', 'ngRoute', 'ngAnimate','ngTouch','ngCookies'])
.config(function($routeProvider){
	$routeProvider
	//首页
	.when("/",{
		templateUrl:"template/home.html",
		controller:"homes",
	})
	.when("/home",{
		templateUrl:"template/home.html",
		controller:"homes",
	})
	.when("/yljf",{
		templateUrl:"template/yljf.html",
		controller:"yljf",
	})
	.when("/help",{
		templateUrl:"template/help.html",
		controller:"help",
	})
	.when("/chanpin",{
		templateUrl:"template/chanpin.html",
		controller:"chanpin"
	})
	.when("/fxpc",{
		templateUrl:"template/fxpc.html",
		controller:"fxpc"
	})
	.when("/pcend",{
		templateUrl:"template/pcend.html",
		controller:"pcend"
	})
	.when("/chanpinxq",{
		templateUrl:"template/chanpinxq.html",
		controller:"chanpinxq"
	})
	.when("/calc",{
		templateUrl:"template/calc.html",
		controller:"calc"
	})
	.when("/xgxy",{
		templateUrl:"template/xgxy.html",
		controller:"xgxy"
	})
	.when("/jijinxq",{
		templateUrl:"template/jijinxq.html",
		controller:"jijinxq"
	})
	.when("/faxian",{
		templateUrl:"template/faxian.html",
		controller:"faxian"
	})
	.when("/vip",{
		templateUrl:"template/vip.html",
		controller:"vip"
	})
	.when("/hytq",{
		templateUrl:"template/hytq.html",
		controller:"hytq"
	})
	.when("/tqxq",{
		templateUrl:"template/tqxq.html",
		controller:"tqxq"
	})
	.when("/qd",{
		templateUrl:"template/qd.html",
		controller:"qd"
	})
	.when("/jfsc",{
		templateUrl:"template/jfsc.html",
		controller:"jfsc"
	})
	.when("/shopxq",{
		templateUrl:"template/shopxq.html",
		controller:"shopxq"
	})
	.when("/qrdd",{
		templateUrl:"template/qrdd.html",
		controller:"qrdd"
	})
	.when("/dhcg",{
		templateUrl:"template/dhcg.html",
		controller:"dhcg"
	})
	.when("/dhjl",{
		templateUrl:"template/dhjl.html",
		controller:"dhjl"
	})
	.when("/seladd",{
		templateUrl:"template/seladd.html",
		controller:"seladd"
	})
	.when("/add",{
		templateUrl:"template/add.html",
		controller:"add"
	})
	.when("/deladd",{
		templateUrl:"template/deladd.html",
		controller:"deladd"
	})
	.when("/tjdz",{
		templateUrl:"template/tjdz.html",
		controller:"tjdz"
	})
	.when("/jf",{
		templateUrl:"template/jf.html",
		controller:"jf"
	})
	.when("/core",{
		templateUrl:"template/core.html",
		controller:"core"
	})
	.when("/dqlc",{
		templateUrl:"template/dqlc.html",
		controller:"dqlc"
	})
	.when("/sgxq",{
		templateUrl:"template/sgxq.html",
		controller:"sgxq"
	})
	.when("/skxq",{
		templateUrl:"template/skxq.html",
		controller:"skxq"
	})
	.when("/kxtdd",{
		templateUrl:"template/kxtdd.html",
		controller:"kxtdd"
	})
	.when("/xtjl",{
		templateUrl:"template/xtjl.html",
		controller:"xtjl"
	})
	.when("/xtjlxq",{
		templateUrl:"template/xtjlxq.html",
		controller:"xtjlxq"
	})
	.when("/dzsy",{
		templateUrl:"template/dzsy.html",
		controller:"dzsy"
	})
	.when("/zhsz",{
		templateUrl:"template/zhsz.html",
		controller:"zhsz"
	})
	.when("/bdxx",{
		templateUrl:"template/bdxx.html",
		controller:"bdxx"
	})
	.when("/smxx",{
		templateUrl:"template/smxx.html",
		controller:"smxx"
	})
	.when("/wdsj",{
		templateUrl:"template/wdsj.html",
		controller:"wdsj"
	})
	.when("/bank",{
		templateUrl:"template/bank.html",
		controller:"bank"
	})
	.when("/ghyhk",{
		templateUrl:"template/ghyhk.html",
		controller:"ghyhk"
	})
	.when("/ghyhk2",{
		templateUrl:"template/ghyhk2.html",
		controller:"ghyhk2"
	})
	.when("/xxzx",{
		templateUrl:"template/xxzx.html",
		controller:"xxzx"
	})
	.when("/wdfl",{
		templateUrl:"template/wdfl.html",
		controller:"wdfl"
	})
	.when("/grxx",{
		templateUrl:"template/grxx.html",
		controller:"grxx"
	})
	.when("/aqkl",{
		templateUrl:"template/aqkl.html",
		controller:"aqkl"
	})
	.when("/zd",{
		templateUrl:"template/zd.html",
		controller:"zd"
	})
	.when("/rz",{
		templateUrl:"template/rz.html",
		controller:"rz"
	})
	.when("/rz2",{
		templateUrl:"template/rz2.html",
		controller:"rz2"
	})
	.when("/login",{
		templateUrl:"template/login.html",
		controller:"login"
	})
	.when("/yzmlogin",{
		templateUrl:"template/yzmlogin.html",
		controller:"yzmlogin"
	})
	.when("/register",{
		templateUrl:"template/register.html",
		controller:"register"
	})
	.when("/czmm",{
		templateUrl:"template/czmm.html",
		controller:"czmm"
	})
	.when("/czmm2",{
		templateUrl:"template/czmm2.html",
		controller:"czmm2"
	})
	.when("/xgmm",{
		templateUrl:"template/xgmm.html",
		controller:"xgmm"
	})
	.otherwise({
	    redirectTo: "/"
	})
})